import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider, Layout } from "antd";


const { Header, Content, Footer } = Layout;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
      direction="rtl"
      theme={{
        token: {
          // Seed Token
          colorPrimary: "rgba(115, 57, 237,  1)",
          fontFamily: "iranSans",
        },
      }}
    >
      <html lang="en">
        <body>{children}</body>
      </html>
    </ConfigProvider>
  );
}
